const timeZoneToCurrency = {
    // 🌎 North America
    "America/New_York": "USD",
    "America/Chicago": "USD",
    "America/Los_Angeles": "USD",
    "America/Toronto": "CAD",
    "America/Vancouver": "CAD",
    "America/Mexico_City": "MXN",

    // 🌍 South America
    "America/Argentina/Buenos_Aires": "ARS",
    "America/Sao_Paulo": "BRL",
    "America/Lima": "PEN",
    "America/Bogota": "COP",
    "America/Santiago": "CLP",

    // 🌍 Europe
    "Europe/London": "GBP",
    "Europe/Berlin": "EUR",
    "Europe/Paris": "EUR",
    "Europe/Madrid": "EUR",
    "Europe/Rome": "EUR",
    "Europe/Stockholm": "SEK",
    "Europe/Zurich": "CHF",
    "Europe/Oslo": "NOK",

    // 🌍 Middle East
    "Asia/Dubai": "AED",
    "Asia/Riyadh": "SAR",
    "Asia/Tehran": "IRR",
    "Asia/Istanbul": "TRY",
    "Asia/Baghdad": "IQD",
    "Asia/Jerusalem": "ILS",

    // 🌏 Asia
    "Asia/Tokyo": "JPY",
    "Asia/Shanghai": "CNY",
    "Asia/Hong_Kong": "HKD",
    "Asia/Kolkata": "INR",
    "Asia/Calcutta": "INR",
    "Asia/Singapore": "SGD",
    "Asia/Seoul": "KRW",
    "Asia/Bangkok": "THB",
    "Asia/Kuala_Lumpur": "MYR",
    "Asia/Jakarta": "IDR",

    // 🌍 Africa
    "Africa/Johannesburg": "ZAR",
    "Africa/Cairo": "EGP",
    "Africa/Nairobi": "KES",
    "Africa/Lagos": "NGN",
    "Africa/Algiers": "DZD",

    // 🌏 Australia & Oceania
    "Australia/Sydney": "AUD",
    "Australia/Melbourne": "AUD",
    "Pacific/Auckland": "NZD",
    "Pacific/Fiji": "FJD",
};


const supportedCurrencies = {
    BTC: "₿",
    ETH: "Ξ",
    LTC: "Ł",
    BCH: "₿",
    EOS: "ε",
    XRP: "✕",
    XLM: "★",
    YFI: "Y",
    USD: "$",
    AED: "د.إ",
    ARS: "$",
    AUD: "A$",
    BDT: "৳",
    BHD: ".د.ب",
    BMD: "$",
    BRL: "R$",
    CAD: "C$",
    CHF: "CHF",
    CLP: "$",
    CNY: "¥",
    CZK: "Kč",
    DKK: "kr",
    EUR: "€",
    GBP: "£",
    GEL: "₾",
    HKD: "HK$",
    HUF: "Ft",
    IDR: "Rp",
    ILS: "₪",
    INR: "₹",
    JPY: "¥",
    KRW: "₩",
    KWD: "KD",
    LKR: "Rs",
    MMK: "K",
    MXN: "$",
    MYR: "RM",
    NGN: "₦",
    NOK: "kr",
    NZD: "NZ$",
    PHP: "₱",
    PKR: "₨",
    PLN: "zł",
    RUB: "₽",
    SAR: "﷼",
    SEK: "kr",
    SGD: "S$",
    THB: "฿",
    TRY: "₺",
    TWD: "NT$",
    UAH: "₴",
    VEF: "Bs",
    VND: "₫",
    ZAR: "R",
    XDR: "SDR",
    XAG: "🜚",
    XAU: "🜛",
    BITS: "ƀ",
};
export { timeZoneToCurrency };
export default supportedCurrencies;
